apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    tier: frontend
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
    - name: myport
      port: 8037 #this is the port to access the localhost
      protocol: TCP
      targetPort: 3040 # this is the target port
  type: LoadBalancer
