apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3 # this means 3 replicas will be made for each container so 6 containers in total
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: mynode
          # imagePullPolicy: Never
          image: somanshahuja/myimage:1.1.1
          ports:
            - containerPort: 3040
